"use client";

import { BrowserMultiFormatReader, IScannerControls } from "@zxing/browser";
import { DecodeHintType } from "@zxing/library";
import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, Barcode, Camera, CircleHelp, ImagePlus, Info, Leaf, LoaderCircle, ScanLine, Sparkles, SwitchCamera, X } from "lucide-react";
type Result = { name: string; category?: string; score: number; grade: string; summary: string; calories: number; protein: number; carbs: number; fat: number; highlights: string[]; concerns?: string[]; alternatives?: string[]; caution: string };
type ScanMode = "food" | "barcode";

export default function Home() {
  const [mode, setMode] = useState<ScanMode>("food"), [cameraOn, setCameraOn] = useState(false), [entered, setEntered] = useState(false), [facing, setFacing] = useState<"environment" | "user">("environment");
  const [loading, setLoading] = useState(false), [result, setResult] = useState<Result | null>(null), [error, setError] = useState(""), [cameraError, setCameraError] = useState("");
  const video = useRef<HTMLVideoElement>(null), stream = useRef<MediaStream | null>(null), barcodeControls = useRef<IScannerControls | null>(null), imageInput = useRef<HTMLInputElement>(null);
  const stopCamera = useCallback(() => { barcodeControls.current?.stop(); barcodeControls.current = null; stream.current?.getTracks().forEach(t => t.stop()); stream.current = null; if (video.current) video.current.srcObject = null; }, []);
  const barcodeResult = useCallback(async (code: string) => { stopCamera(); setLoading(true); try { const r = await fetch(`/api/barcode?code=${encodeURIComponent(code)}`); const data = await r.json(); if (!r.ok) throw new Error(data.error); setResult(data); } catch (e) { setError(e instanceof Error ? e.message : "We couldn’t look up that barcode."); } finally { setLoading(false); } }, [stopCamera]);
  useEffect(() => {
    if (!cameraOn || !video.current) return; let cancelled = false;
    const open = async () => { setCameraError(""); stopCamera(); try {
      const constraints = { video: { facingMode: { ideal: facing }, width: { ideal: 1920 }, height: { ideal: 1080 } }, audio: false };
      if (mode === "barcode") { const reader = new BrowserMultiFormatReader(new Map([[DecodeHintType.TRY_HARDER, true]])); const controls = await reader.decodeFromConstraints(constraints, video.current!, scan => { if (scan && !cancelled) { cancelled = true; controls.stop(); barcodeResult(scan.getText()); } }); if (cancelled) controls.stop(); else barcodeControls.current = controls; }
      else { const media = await navigator.mediaDevices.getUserMedia(constraints); if (cancelled) media.getTracks().forEach(t => t.stop()); else { stream.current = media; video.current!.srcObject = media; await video.current!.play(); } }
    } catch { if (!cancelled) setCameraError("Camera access is off. Click the camera icon in your browser’s address bar, allow it, then try again."); } };
    open(); return () => { cancelled = true; stopCamera(); };
  }, [cameraOn, facing, mode, barcodeResult, stopCamera]);
  useEffect(() => () => stopCamera(), [stopCamera]);
  const analyze = async (image: string) => { setLoading(true); setError(""); try { const r = await fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setResult(data); } catch (e) { setError(e instanceof Error ? e.message : "The food scan did not finish."); } finally { setLoading(false); } };
  const takeFoodScan = () => { const source = video.current; if (!source || !source.videoWidth) return imageInput.current?.click(); const c = document.createElement("canvas"), ratio = Math.min(1, 1400 / source.videoWidth); c.width = Math.round(source.videoWidth * ratio); c.height = Math.round(source.videoHeight * ratio); c.getContext("2d")?.drawImage(source, 0, 0, c.width, c.height); analyze(c.toDataURL("image/jpeg", .8)); };
  const file = (f?: File) => { if (!f) return; const reader = new FileReader(); reader.onload = () => analyze(reader.result as string); reader.readAsDataURL(f); };
  const changeMode = (next: ScanMode) => { if (next !== mode) { setMode(next); setCameraOn(true); setCameraError(""); } };
  const reset = () => { setResult(null); setError(""); setCameraError(""); setCameraOn(false); stopCamera(); };
  const scanAgain = () => { setResult(null); setError(""); setCameraError(""); setCameraOn(true); };
  const grade = result?.grade?.toLowerCase() || "a";
  if (!entered) return <main className="home-screen"><header><div className="wordmark"><span><Leaf size={17} fill="currentColor" /></span>NutriLens</div><button className="help"><CircleHelp size={20} /></button></header><div className="home-copy"><p><Sparkles size={13} /> SMART FOOD SCANNER</p><h1>Know your<br /><i>next bite.</i></h1><span>Food scores made simple.</span></div><div className="home-card"><div className="home-bowl">🥑<b>🥕</b><i>🍅</i></div><div><strong>Scan food</strong><span>Photo or barcode</span></div><em>01</em></div><button className="enter" onClick={() => { setEntered(true); setCameraOn(true); }}><span><Camera size={22} /></span> Swipe to scan <b>›</b></button></main>;
  return <main className="app-shell"><section className={`camera-screen ${cameraOn ? "camera-active" : ""}`}><video ref={video} muted playsInline className="camera-feed" /><div className="camera-shade" />
    <header><div className="wordmark"><span><Leaf size={17} fill="currentColor" /></span>NutriLens</div><button className="help"><CircleHelp size={20} /></button></header>
    <div className="top-copy"><h1>{mode === "food" ? "Food scan" : "Barcode scan"}</h1></div>
    <div className={`focus-frame ${mode === "barcode" ? "barcode-frame" : ""}`}><i /><i /><i /><i />{mode === "barcode" && <div className="scan-beam" />}</div>{!cameraOn && <div className="camera-empty"><div className="food-glow">🥗</div><p>Point, scan, understand.</p></div>}{cameraError && <div className="camera-error">{cameraError}</div>}
    <div className="bottom-panel"><div className="mode-switch"><button className={mode === "food" ? "selected" : ""} onClick={() => changeMode("food")}><Camera size={17} /> Food</button><button className={mode === "barcode" ? "selected" : ""} onClick={() => changeMode("barcode")}><Barcode size={18} /> Barcode</button></div><div className="scan-actions"><button className="gallery" onClick={() => imageInput.current?.click()} aria-label="Choose photo"><ImagePlus size={22} /></button><button className="shutter" onClick={() => mode === "food" && takeFoodScan()} aria-label="Scan"><span>{mode === "barcode" ? <ScanLine size={31} /> : <Camera size={30} />}</span></button><button className="flip" onClick={() => { setFacing(v => v === "environment" ? "user" : "environment"); }} aria-label="Switch camera"><SwitchCamera size={22} /></button></div></div>
  </section><input ref={imageInput} type="file" accept="image/*" capture="environment" hidden onChange={e => file(e.target.files?.[0])} />
  {(loading || result || error) && <div className="result-sheet"><div className="sheet-card"><button className="close-sheet" onClick={reset}><X size={20} /></button>{loading && <div className="scan-state"><LoaderCircle className="spin" size={38} /><h2>Checking your food</h2><p>NutriLens is reading the details.</p></div>}{error && <div className="scan-state"><Info size={37} /><h2>That didn’t scan</h2><p>{error}</p><button className="retry" onClick={scanAgain}>Try again</button></div>}{result && !loading && <div className="result-content"><div className="result-heading"><div><p>{result.category || "FOOD"} · NUTRITION SCORE</p><h2>{result.name}</h2><span>{result.summary}</span></div><div className={`score-ring grade-${grade}`}><b>{Math.round(result.score)}</b><small>/ 100</small><em>{result.grade}</em></div></div><div className="nutrition-row"><div><b>{result.calories || "—"}</b><span>Calories</span></div><div><b>{result.protein || "—"}g</b><span>Protein</span></div><div><b>{result.carbs || "—"}g</b><span>Carbs</span></div><div><b>{result.fat || "—"}g</b><span>Fat</span></div></div><div className="insights">{result.highlights?.map((item, i) => <p key={i}><i>✓</i>{item}</p>)}</div>{result.concerns?.length ? <div className="concerns"><strong><AlertTriangle size={16} /> Watch for</strong>{result.concerns.map((item, i) => <p key={i}>{item}</p>)}</div> : null}{result.alternatives?.length ? <div className="alternatives"><strong>Better swaps</strong>{result.alternatives.map((item, i) => <span key={i}>{item}</span>)}</div> : null}<p className="note">{result.caution}</p><button className="retry wide" onClick={scanAgain}>Scan another food</button></div>}</div></div>}</main>;
}
